apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-map 
  namespace: default
  labels:
    app: status-map
    version: v1.20
  annotations:
    kubernetes.io/change-cause: "v1.20"
spec:
  selector:
    matchLabels: 
      app: status-map
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: status-map
        version: v1.16
    spec:
      restartPolicy: Always
      containers:
        - name: status-map
          image: gcr.io/iplanrio-status/status-map:1.20
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
          imagePullPolicy: Always
          ports:
            - name: map
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: map
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: map
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: status-map

