apiVersion: v1
kind: Service
metadata:
  name: status-map
  namespace: default
  labels:
    app: status-map
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: status-map
